#BuildNo:7
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flask-app-demo-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-flask-app-demo-01
  template:
    metadata:
      labels:
        app: basic-flask-app-demo-01
    spec:
      containers:
        - name: basic-flask-app-demo-01
          image: x64nik/argo-flask-apps:7
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-flask-app-demo-01
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5050
  selector:
    app: basic-flask-app-demo-01
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: basic-flask-app-demo-01
  # namespace: default
spec:
  entryPoints:
    - websecure
  tls:
  hosts:
  - flask.local.rushikesh.de
  secretName: ssl-cert
  routes:
    - kind: Rule
      match: Host(`flask.local.rushikesh.de`)
      priority: 10
      services:
        - name: basic-flask-app-demo-01
          port: 80

